# Generated by Django 3.2 on 2023-02-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketsector',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
