# Generated by Django 3.2 on 2023-02-09 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
        ('platform_admin', '0002_alter_marketsector_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsectorbulkdata',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.city'),
        ),
        migrations.AddField(
            model_name='marketsectorbulkdata',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.country'),
        ),
        migrations.AddField(
            model_name='marketsectorbulkdata',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.state'),
        ),
    ]
