# Generated by Django 3.2 on 2023-02-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('platform_admin', '0003_auto_20230209_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsector',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='profile_followers', to='accounts.Profile'),
        ),
    ]
