# Generated by Django 3.2 on 2023-02-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0004_marketsector_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketsector',
            name='followers',
        ),
    ]
