# Generated by Django 3.2 on 2023-02-13 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_auto_20230213_1451'),
        ('platform_admin', '0006_historical'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.city'),
        ),
        migrations.AddField(
            model_name='historical',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.country'),
        ),
        migrations.AddField(
            model_name='historical',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.state'),
        ),
    ]
