# Generated by Django 3.2 on 2023-02-13 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_auto_20230213_1451'),
        ('platform_admin', '0007_auto_20230213_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical',
            name='geo_political_zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.geopoliticalzone'),
        ),
        migrations.AddField(
            model_name='marketsector',
            name='geo_political_zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.geopoliticalzone'),
        ),
    ]
