# Generated by Django 3.2 on 2023-02-14 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_clan'),
        ('platform_admin', '0008_auto_20230213_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical',
            name='clan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.clan'),
        ),
    ]
