# Generated by Django 3.2 on 2023-02-14 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_clan'),
        ('platform_admin', '0009_historical_clan'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsector',
            name='clan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.clan'),
        ),
    ]
