# Generated by Django 3.2 on 2023-02-14 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0012_geopoliticalcategory_historicalcategory_marketsectorcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='geopoliticaldata',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_admin.geopoliticalcategory'),
        ),
        migrations.AddField(
            model_name='historical',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_admin.historicalcategory'),
        ),
        migrations.AddField(
            model_name='marketsector',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_admin.marketsectorcategory'),
        ),
        migrations.AddField(
            model_name='marketsectorbulkdata',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_admin.marketsectorcategory'),
        ),
    ]
