# Generated by Django 3.2 on 2023-02-16 09:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0014_marketsector_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketsector',
            name='content',
        ),
        migrations.AlterField(
            model_name='marketsector',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
