# Generated by Django 3.2 on 2023-02-16 09:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0015_auto_20230216_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsector',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
