# Generated by Django 3.2 on 2023-02-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0016_marketsector_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketsector',
            name='content',
        ),
    ]
