# Generated by Django 3.2 on 2024-09-04 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search_data', '0006_rename_main_video_searchdataimages_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdata',
            name='user_import',
            field=models.ManyToManyField(blank=True, related_name='search_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
