# Generated by Django 3.2 on 2024-09-06 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search_data', '0006_rename_main_video_searchdataimages_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchDataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('search_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search_data.searchdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_data_import', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SearchDataBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('search_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search_data.searchdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_data_bookmark', to='accounts.profile')),
            ],
        ),
    ]
