# Generated by Django 3.2 on 2024-10-31 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_data', '0007_searchdatabookmark_searchdataimport_searchhistory'),
        ('search_data', '0007_searchdatahistory_searchdatasaved'),
    ]

    operations = [
    ]
