# Generated by Django 3.2 on 2024-11-03 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_is_deleted'),
        ('search_data', '0007_searchdatabookmark_searchdataexport_searchdatahistory_searchdataimport_searchdatasaved_searchdatasha'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDataDownloads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('search_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search_data.searchdata')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile')),
            ],
        ),
    ]
