# Generated by Django 3.2 on 2024-10-31 12:42

from django.db import migrations, models
import django.db.models.deletion
import search_data.helpers.validate_filextension


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_is_deleted'),
        ('search_data', '0007_searchdatabookmark_searchdatahistory_searchdataimport_searchdatasaved_searchdateshare'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', validators=[search_data.helpers.validate_filextension.validate_file_extension])),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_data_upload', to='accounts.profile')),
            ],
        ),
    ]
